# Site settings
title: PRML

email: "swear013@gmail.com"
url: "http://norman3.github.io"
github_url: "http://github.com/norman3/prml"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/norman3"
baseurl: "/prml"
disqus_shortname: norman3github

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
