# Site settings
title: Vision-opencv

email: "dowkkr94@gmail.com"
url: "http://hyunahoh.github.io"
github_url: "http://github.com/hyunahOh/vision-opencv"
# github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/hyunahOh"
baseurl: "/vision-opencv"
disqus_shortname: hyunahOh-github

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
 
